// <auto-generated />
using Api.Util;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiAirsoft.Migrations
{
    [DbContext(typeof(AirsoftDbContext))]
    [Migration("20230311154101_AddedFirstMigrattion")]
    partial class AddedFirstMigrattion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Api.Modelos.Armas.Accesorio", b =>
                {
                    b.Property<int>("Cod_Accesorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Accesorio"), 1L, 1);

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Cod_Accesorio");

                    b.ToTable("Accesorio");
                });

            modelBuilder.Entity("Api.Modelos.Armas.Accion", b =>
                {
                    b.Property<int>("Cod_Accion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Accion"), 1L, 1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Cod_Accion");

                    b.ToTable("Accion");
                });

            modelBuilder.Entity("Api.Modelos.Armas.Arma", b =>
                {
                    b.Property<int>("Cod_Referencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Referencia"), 1L, 1);

                    b.Property<int>("Capacidad_Cargador")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HopUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Longitud")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Potencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Velocidad")
                        .HasColumnType("int");

                    b.HasKey("Cod_Referencia");

                    b.ToTable("Armas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Arma");
                });

            modelBuilder.Entity("Api.Modelos.Armas.Disparo", b =>
                {
                    b.Property<int>("Cod_Disparo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Disparo"), 1L, 1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Cod_Disparo");

                    b.ToTable("Disparo");
                });

            modelBuilder.Entity("Api.Modelos.Color", b =>
                {
                    b.Property<int>("Cod_Color")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Color"), 1L, 1);

                    b.Property<string>("Hexadecimal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Cod_Color");

                    b.ToTable("Colores");
                });

            modelBuilder.Entity("ArmaColor", b =>
                {
                    b.Property<int>("ArmasCod_Referencia")
                        .HasColumnType("int");

                    b.Property<int>("ColoresCod_Color")
                        .HasColumnType("int");

                    b.HasKey("ArmasCod_Referencia", "ColoresCod_Color");

                    b.HasIndex("ColoresCod_Color");

                    b.ToTable("ArmaColor");
                });

            modelBuilder.Entity("Api.Modelos.Armas.Escopeta", b =>
                {
                    b.HasBaseType("Api.Modelos.Armas.Arma");

                    b.Property<int>("Capacidad_Cartucho")
                        .HasColumnType("int");

                    b.Property<bool>("Cartuchos_Incluidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasDiscriminator().HasValue("Escopeta");
                });

            modelBuilder.Entity("Api.Modelos.Armas.Francotirador", b =>
                {
                    b.HasBaseType("Api.Modelos.Armas.Arma");

                    b.Property<bool>("Bipode_Incluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Mira_Incluida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasDiscriminator().HasValue("Francotirador");
                });

            modelBuilder.Entity("Api.Modelos.Armas.Fusil", b =>
                {
                    b.HasBaseType("Api.Modelos.Armas.Arma");

                    b.HasDiscriminator().HasValue("Fusil");
                });

            modelBuilder.Entity("Api.Modelos.Armas.Pistola", b =>
                {
                    b.HasBaseType("Api.Modelos.Armas.Arma");

                    b.HasDiscriminator().HasValue("Pistola");
                });

            modelBuilder.Entity("Api.Modelos.Armas.Subfusil", b =>
                {
                    b.HasBaseType("Api.Modelos.Armas.Arma");

                    b.HasDiscriminator().HasValue("Subfusil");
                });

            modelBuilder.Entity("ArmaColor", b =>
                {
                    b.HasOne("Api.Modelos.Armas.Arma", null)
                        .WithMany()
                        .HasForeignKey("ArmasCod_Referencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modelos.Color", null)
                        .WithMany()
                        .HasForeignKey("ColoresCod_Color")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
